# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Surreptus"

# A description of your site for meta tag, search engine results.
description: "A collection of notes about cycling, photography, and programming."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://surreptus.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Tags
    url: /tags/

# The shortname for your Disqus site to enable comments.
# disqus: justgoodthemes

# Colors
accent_color: '#1b134f'

# Site footer
footer:
  content: "Â© GPL Surretpus"
  has_social: false

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
